services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=helpdesk
    volumes:
      - ./docker:/docker-entrypoint-initdb.d

  pg_test:
    image: bitnami/postgresql:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=helpdesk_test
    volumes:
      - ./docker:/docker-entrypoint-initdb.d